### ISSUE TITLE
播放不了...

### ISSUE THREAD

**Issue by maxwell44** [Chris-Pan/JPVideoPlayer#1]
我Xcode8,运行了Demo,似乎播放不了

**Comment by Chris-Pan** [comment]
我还没使用Xcode8运行过, 你报了什么错, 我晚上回去试一下回复你.

**Comment by maxwell44** [comment]
就是没有任何错误……


发自网易邮箱大师
在2016年09月21日 15:29，Chris-Pan 写道:

我还没使用Xcode8运行过, 你报了什么错, 我晚上回去试一下回复你.

**Comment by Chris-Pan** [comment]
抱歉啊,我装好Xcode8以后, 模拟器一直打不开, 无法初始化, 我公司的电脑和我的电脑都是, 暂时没找到怎么解决模拟器的问题. 如果你电脑上有Xcode7.3的话, 建议用这个版本打开, 因为我当时写的时候就是用这个版本的Xcode写的.

**Comment by maxwell44** [comment]
我用Xcode8+iPhone7真机测试  无网络连接

**Comment by Chris-Pan** [comment]
刚测试了, 用xcode8完美运行, 不知道你那边是什么情况?
![snip20160922_1](https://cloud.githubusercontent.com/assets/14839923/18742455/e299093a-80e6-11e6-9240-3f0272a21c84.png)

**Comment by maxwell44** [comment]
真机还是模拟器呢

**Comment by Chris-Pan** [comment]
模拟器和真机都试了, 没有问题.
