### ISSUE TITLE
无后缀音频无法播放

### ISSUE THREAD

**Issue by mxyolande** [Chris-Pan/JPVideoPlayer#11]
修改demo中的播放列表.
self.pathStrings = @[
                         @"http://tts.baidu.com/text2audio?idx=1&cuid=baidu_speech_demo&cod=2&lan=zh&ctp=1&pdt=1&spd=5&per=2&vol=5&pit=5&tex=you",
                         @"http://tts.baidu.com/text2audio?idx=1&cuid=baidu_speech_demo&cod=2&lan=zh&ctp=1&pdt=1&spd=5&per=2&vol=5&pit=5&tex=baidu",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=users",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=download",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=controller",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=view",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=model",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=video",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=distant",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=only",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=things",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=were",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=universal",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=stare",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=made",
                         @"http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&spd=3&text=but",
                         ];
貌似没有后缀就无法播放, 不知道应该怎么处理, 正常使用avplayer可以.
在status的kvo打印error为: 

Error Domain=AVFoundationErrorDomain Code=-11828 "Cannot Open" UserInfo={NSUnderlyingError=0x174054dc0 {Error Domain=NSOSStatusErrorDomain Code=-12847 "(null)"}, NSLocalizedFailureReason=This media format is not supported., NSLocalizedDescription=Cannot Open}

**Comment by Chris-Pan** [comment]
建议你自己根据这个错误去排一下问题. 谢谢支持!!
