### ISSUE TITLE
无法边下边播，只能下完才播放

### ISSUE THREAD

**Issue by WhatIsLionKing** [Chris-Pan/JPVideoPlayer#18]
下载的数据在
respondWithDataForRequest:(AVAssetResourceLoadingDataRequest *)dataRequest
方法中处理完了之后没有播放

**Comment by WhatIsLionKing** [comment]
试了很多个标准视频链接都是这样

**Comment by Chris-Pan** [comment]
有些服务器是不支持边下边播的, 我司用的是腾讯云, 在框架中没有问题, 请您排查一下您的视频寄存服务商是否支持. 谢谢
