### ISSUE TITLE
播放完成定制

### ISSUE THREAD

**Issue by LoveDou** [Chris-Pan/JPVideoPlayer#19]
目前播放完成后默认是seek到0，个人建议播放完成应该给一个回调，让开发者可以自定义播放完成的后续行为，这样的话定制性更强

**Comment by Chris-Pan** [comment]
你的需求场景是什么，帮忙说一下。

**Comment by LoveDou** [comment]
不好意思，才可看到邮件，你写的非常不错，给你点个赞！我现在在做一个视频广告展示，广告播放完成后会有一个试玩游戏的button，这个后续的动作需要定制，我已经在你的基础上添加了这个播放完成回调。
另外有一个小小的建议，封装成一个自定义的tableview，然后开发者可以直接使用tableview，只需要几行代码就可以实现这个功能，我在你的基础上也封装好了^-^。

**Comment by LoveDou** [comment]
不好意思，才可看到邮件，你写的非常不错，给你点个赞！我现在在做一个视频广告展示，广告播放完成后会有一个试玩游戏的button，这个后续的动作需要定制，我已经在你的基础上添加了这个播放完成回调。
另外有一个小小的建议，封装成一个自定义的tableview，然后开发者可以直接使用tableview，只需要几行代码就可以实现这个功能，我在你的基础上也封装好了^-^。

**Comment by Chris-Pan** [comment]
已经采纳了你的建议, 谢谢支持!!!
