### ISSUE TITLE
你这个不能播放啊，不知道怎么回事？

### ISSUE THREAD

**Issue by youbooks** [Chris-Pan/JPVideoPlayer#2]
![image](https://cloud.githubusercontent.com/assets/17697229/19849961/ee14ec7a-9f90-11e6-8c5e-35a9165998d5.png)

**Comment by youbooks** [comment]
我代码是这样写的：
- (void)viewDidLoad {
    [super viewDidLoad];
    self.showView = [[UIView alloc] init];
    self.showView.backgroundColor = [UIColor grayColor];
    self.showView.frame = CGRectMake(0, 0, 320, 280);
    [self.view addSubview:self.showView];
    
    JPVideoPlayer *player = [JPVideoPlayer sharedInstance];
    [player playWithUrl:[NSURL URLWithString:@"http://v4ttyey-10001453.video.myqcloud.com/Microblog/288-4-1452304375video1466172731.mp4"] showView:self.showView];
    
}

引入你的这个插件，但是程序运行起来，视频没有播放啊，我换了好几个视频url 地址都不行

**Comment by Chris-Pan** [comment]
![snip20161031_1](https://cloud.githubusercontent.com/assets/14839923/19858473/84be236e-9fbc-11e6-8019-1da7a3600cb2.png)
我试了一下, 能播放啊, 没有问题. 是不是你没有在info.plist里配置可以访问http的URL? 从iOS8开始, 苹果提高了URL的安全性, 默认只能访问https的URL, 如果你不知道如何配置, 请按照这篇文章 (http://www.hangge.com/blog/cache/detail_822.html) 的方式试试看, 如果还不行, 你可以再留言.
