### ISSUE TITLE
无法显示进度条

### ISSUE THREAD

**Issue by jiangqc5656** [Chris-Pan/JPVideoPlayer#22]
现在只有下载的进度条，我如果需要显示播放的进度条该如何设置？
本来想要自己用NSTimer 来显示，发现你的AVPlayer 和 AVURLAsset 设为了私有变量，并没有开发出来。希望你能有好的方法解决掉这个问题。
我暂时在项目中修改了你的这部分代码，希望下一个版本你能把这个功能添加进去。

**Comment by Chris-Pan** [comment]
建议很好, 下个版本可能会加进去. 谢谢支持!
