### ISSUE TITLE
cocoapods 还是 1.5.0版本

### ISSUE THREAD

**Issue by ntian2** [Chris-Pan/JPVideoPlayer#23]
cocoapods 还是 1.5.0版本

**Comment by Chris-Pan** [comment]
请先删除你本地的 cocoapods 缓存列表，重新再试一下，谢谢支持！！

**Comment by ntian2** [comment]
删除了 再装了一次 还是 1.5.0

**Comment by Chris-Pan** [comment]
这种情况我也碰到了，我当时卸载 Cocoapods 重装才能搜到，但是如果网络环境较差不建议这么做。建议先找一台没有搜索过这个框架的 Mac 电脑搜一下，如果能搜到就在那台电脑上执行 pod install 就好了。希望能帮到你！

**Comment by ntian2** [comment]
谢了。我把 缓存清了 然后把 podFile.lock 删了 再装就好了
