### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by butcheryl** [Chris-Pan/JPVideoPlayer#24]
1. 在 `UIView+PlayerStatusAndDownloadIndicator` 中，像 `progressView` 这种比较大众化的属性，是否可以加个前缀(jp_progressView)?😂

2. 是否可以加入，暂停和续播的功能(只是暂停)，包括获取播放状态，场景是正在播放视频，模态出一个界面这个时候暂停播放，界面消失后继续播放。如果调用目前工程中的stop后，其实是移除了item和取消下载。

3. 是否能加入一个新功能，可以设置预加载时间，比如播放视频的时候，当下载的视频达到可播放10s，才播放。

**Comment by Chris-Pan** [comment]
哈，这个可不是小功能，要推翻现有的重新做，等我有空好好考虑一下，最近在忙着找工作，没时间。
