### ISSUE TITLE
加了占位图之后，当视频的宽度不够屏幕宽度时，视频已经在播放了占位图却一直在。

### ISSUE THREAD

**Issue by liuyi520it** [Chris-Pan/JPVideoPlayer#26]
加了占位之后，当视频的宽度不够屏幕宽度时，视频已经在播放了占位图却一直在。能不能把视频没有填充的地方变为黑色的边框，可以以下地址调试
https://bb-bang.com:9002/Test/Vedio/20170425/74ba5b355c6742c084414d4ebd520696.mp4

**Comment by Chris-Pan** [comment]
明白你的意思。谢谢支持。

**Comment by Wuzo** [comment]
我在播放时候 view.image = nil; 初始化设置一下  backgroundcolor

**Comment by Chris-Pan** [comment]
这个问题在最新版中已经解决, 需要时请前往查看, 谢谢支持.
