### ISSUE TITLE
刷新对应的cell视频会卡

### ISSUE THREAD

**Issue by liuyi520it** [Chris-Pan/JPVideoPlayer#27]
在点击cell的方法中
加[self.tableView reloadData];不会卡--作者此版本已经解决了。
但是加[self.tableView reloadRowsAtIndexPaths:[NSArray arrayWithObjects:indexPath,nil] withRowAnimation:UITableViewRowAnimationNone];会停止播放，显示占位图。

**Comment by Chris-Pan** [comment]
你这个情况请自己排查一下代码，谢谢支持！
