### ISSUE TITLE
关于indicatorView的两个bug。

### ISSUE THREAD

**Issue by zangqilong198812** [Chris-Pan/JPVideoPlayer#28]
` else if ([keyPath isEqualToString:@"playbackBufferEmpty"]){
        [self showActivaityIndicatorView];
    }
    else if ([keyPath isEqualToString:@"playbackLikelyToKeepUp"]){
        [self hideActivaityIndicatorView];
    }`

这个地方有点问题。一个是playbackLikelyToKeepUp这个是个BOOL值，observer如果检测到为值变为NO，那么showIndicatorView是没问题的，如果是YES呢？这里没有判断。
第二个是用playbackLikelyToKeepUp来判断是否显示IndicatorView不准确。我用几个视频测试了一下。发现有2-3秒的延迟。这个值得注释也说了，“In this event the playback buffer has
	reached capacity but there isn't the statistical data to support a prediction that playback is likely to 
	keep up”
只是表明buffer有了，但不代表立即可以播放。
目前来看最准确的检测什么时候隐藏和显示IndicatorView的还是observe player的rate。
如果不是用户暂停的情况下，rate == 0肯定表示加载中，>0表示正在播放，那肯定代表已经加载完成了。

现在播放器的功能有点弱。我觉得可以加入快进快退（scrub）的功能，和进度的delegate。
缓存是写的确实很好。

**Comment by Chris-Pan** [comment]
谢谢龙哥提醒，bug 我待会改，但是加功能这个可能要 3.0 版本才能上，如果龙哥有时间，可以帮我提交一部分代码，谢谢支持！

**Comment by Chris-Pan** [comment]
龙哥, bug 已经改好了, 但是功能没有加, 等忙完这段时间有空的时候, 写一个 3.0 版本, 再把这些功能加进去. 谢谢资瓷 !

**Comment by zangqilong198812** [comment]
好的。
