### ISSUE TITLE
地址没问题，可有的视频不能播放。

### ISSUE THREAD

**Issue by liuyi520it** [Chris-Pan/JPVideoPlayer#29]
地址是没问题的，可是却播放不了。看了作者的Demo我猜测应该是高度的问题吧，Demo中cell的高度都是一样的，那是视频size比例都同的情况，感觉没问题，给个地址作者试一下就知道了。这个视频地址的size
宽：高=9：16
https://bb-bang.com:9002/Vedio/20170501/35ccdaae4b134697ae97f6107c6a0ede.mp4

**Comment by Chris-Pan** [comment]
请检查视频的问题, 你之前给过我的另一个地址是没有问题的, 谢谢支持.
