### ISSUE TITLE
1分钟以下的视频不能播放

### ISSUE THREAD

**Issue by ceekay1991** [Chris-Pan/JPVideoPlayer#31]
http://gedftnj8mkvfefuaefm.exp.bcevod.com/mda-gmykrs6x4qzhbn95/mda-gmykrs6x4qzhbn95.mp4?playlist=%5B%22hd%22%5D?auth_key=1499222833-0-0-84216f322d930b06a1a01edefe0e71a6&bcevod_channel=searchbox_feed

**Comment by Chris-Pan** [comment]
和视频长度没关系, 具体解决请参照这篇博文 http://blog.sina.com.cn/s/blog_4eb62cbf0102v3kh.html, 谢谢支持.

**Comment by ceekay1991** [comment]
好的，了解。现在下载完了还是一直在转圈，下次打开才可以播放
