### ISSUE TITLE
右滑返回过程中正在播放的视频卡顿

### ISSUE THREAD

**Issue by HugSea** [Chris-Pan/JPVideoPlayer#33]
导航控制器右滑返回过程中, 正在播放的视频卡顿, lz有解决思路吗

**Comment by Chris-Pan** [comment]
在 -viewWillDisapper 方法里要调用停止视频播放的方法, 你调了吗?

**Comment by HugSea** [comment]
能不能像今日头条一样, 在滑动过程中流畅的播放.
