### ISSUE TITLE
七牛的视频地址播放不了

### ISSUE THREAD

**Issue by gank0326** [Chris-Pan/JPVideoPlayer#34]
http://video.toseeapp.com/ios/video/20170115/4c5052f702c3051d9d2e0e20dae94570

**Comment by gank0326** [comment]
网页可以播，也做了CDN加速，支持边下边播的

**Comment by Chris-Pan** [comment]
你这个是不是要做域名跳转?

**Comment by LiberalChen** [comment]
@Chris-Pan http://oo140oc9u.bkt.clouddn.com/60544_1494228991.50696356  我这是音频播放不了~~！

**Comment by crespoxiao** [comment]
我觉得这个不是播放器的问题，应该是加了防盗的处理，需要自己实现相关逻辑
