### ISSUE TITLE
后台切换回来视频会自动播放

### ISSUE THREAD

**Issue by yzkmh** [Chris-Pan/JPVideoPlayer#35]
我已经把JPVideoPlayerPlayVideoTool中becomeAvtive的通知去掉了，在外部控制暂停播放。
但是在暂停状态下，后台切换几次有时会自动播放，持续在前台切到其他界面，视频播放器的状态是暂停，有时候也会自动播放

**Comment by Chris-Pan** [comment]
这个问题在下一个版本已经得到修复, 谢谢支持!

**Comment by hujiudeyang** [comment]
然而现在切换回来的时候会出现短促的声音。。。
