### ISSUE TITLE
第二次播放同一视频时不能播放

### ISSUE THREAD

**Issue by MimiOuO** [Chris-Pan/JPVideoPlayer#38]
正好我最近在做tableview的自动播放，问题是这样的：我们公司视频也是放在七牛上，做了cdn加速，这些视频在浏览器上和安卓上放都没有问题，用你这个框架放的时候当同一视频第二次播放的时候（不论是我来回滑动tableVIew，还是我杀了app重进项目），这个视频就不能播放了。我把我们的视频地址替换掉了你在demo中的地址后也是如此，所以我认为是你对缓存的判断上出了问题（后来我手动清除缓存确实能解决上述问题）。抱歉最近工作比较忙，不能帮助解决问题，希望近期能做出修改，同时也希望jpplayer能越做越好。附上我们测试的视频地址，希望对你有帮助： 
   self.pathStrings = @[
                         @"http://user.xiaomatv.cn/Foc5W0gIy8tjfMzrqB_Gn1zqpL2o",
                         @"http://user.xiaomatv.cn/FovHs997_HNgLsYojH0SiPTUd6T7",
			 @"http://user.xiaomatv.cn/FihpcBVbzxZF687Nf2FEuJjaVGS-",
			 @"http://user.xiaomatv.cn/FpCndpLOATECqfFHXd_VYKl268Pz",
			 @"http://user.xiaomatv.cn/lmNrTlHdjrxDJclcFs3O5tfFmhYW",
			 @"http://user.xiaomatv.cn/FsDEg7qDSxwTQy_E5YyVEdmXYmmX",
			 @"http://user.xiaomatv.cn/FnjwGdu_hy4W-4mie41XT0ssjNAj",
			 @"http://user.xiaomatv.cn/FhRw_KdZlqitbrZOQYNcv62Slzet"

**Comment by Re-cover** [comment]
是的，我们也出现了这样的问题，视频是放在阿里云上的，第二次不能播放
