### ISSUE TITLE
视频播放缓冲黑屏问题

### ISSUE THREAD

**Issue by jiangqc5656** [Chris-Pan/JPVideoPlayer#39]
在视频缓冲是，背景颜色是黑色，建议改成透明。因为我需要在缓冲的时候显示第一帧的图像并且根据下载的进度进行缓慢加载的动画。
我已经手动修改 jp_backgroundLayer 的 backgroundColor为透明
希望下一个版本可以自定义颜色，或者允许用户自定义一个 placeholderImage（只需要在jp_backgroundLayer下面加一层UIViewImageView即可实现）

**Comment by Chris-Pan** [comment]
明白, 谢谢支持.
