### ISSUE TITLE
手势滑动返回过程中，播放变的卡顿？

### ISSUE THREAD

**Issue by EverMe** [Chris-Pan/JPVideoPlayer#4]
目录结构为Nav->vc1->vc2 当player在vc2中，手势滑动返回至vc1的过程中，player会播放卡顿！！！
手势返回的过程中，就是vc2慢慢的手势返回到vc1但始终没放手没有完全的pop回去，手势来回左右滑动，在这个过程中，player会变的卡顿。但是我看bilibili和今日头条等app ，在此过程都没有出现这个问题，项目中又用到这一块，所以想查明原因。但下了很多封装avplayer的demo 发现都有此问题（当然也试了您写的JPVideoPlayer）。

**Comment by Chris-Pan** [comment]
b站他的pop手势是自己封装的, 播放器也是自己封装的, 所以他们可以做很多使用系统的播放器坐不了的事情. 请看这篇文章https://segmentfault.com/a/1190000002739762, 我给你的建议是, 在检测到用户开始pop的时候把视频关掉, 就不会出现那种难看的问题了.

**Comment by EverMe** [comment]
谢谢你的方案，不过vc1中有vc2 player的背景播放，这也是我一直没使用pop时停止的方案的原因。我再研究一下ijkplayer 看能不能找到解决问题的办法。
