### ISSUE TITLE
iPhone6  9.3.5快速滚动出现内存泄漏问题，请帮忙解决下。

### ISSUE THREAD

**Issue by sugerGDev** [Chris-Pan/JPVideoPlayer#8]
![e3147ed8-bd51-4f2f-bec4-4a0d5058673f](https://cloud.githubusercontent.com/assets/15126775/20746614/70ab24ae-b721-11e6-8bbe-9b211898efa0.png)

**Comment by Chris-Pan** [comment]
我已经在demo里测试过, 包括真机和模拟器, 都没有出现leaks, 请结合我的demo来排除你自己的问题, 希望能帮到你.

**Comment by sugerGDev** [comment]
谢谢您的关注，请耐心等待。我晚上再试一试，有肯能您已经修复该问题。
